feat: expand allowed protocols for URLs in repository component
verdaccio/ui pull request #412
Opened 2020-01-08 17:31 UTC by a666

**feature:**

Allow other protocols in repository component

**Description:**

Resolves #301.

2020-01-10 06:22 UTC, DanielRuf requested changes

2020-01-17 22:48 UTC, a666 commented
Sorry about the lack of updates, I just changed jobs and probably won't have the time to work on this feature. If someone else wants to have a go at it, they are welcome.

2020-01-18 09:34 UTC, juanpicado commented
Thanks for the update @a666 very appreciated, let's see whether someone wants to PR this PR :)

2021-04-27 19:47 UTC, juanpicado approved these changes
good enough for now, I'll add test on the main repo later on.

2021-04-27 19:54 UTC, merged